server:
  port: 8089
  
logging:
  config: classpath:log4j2.xml
dubbo:
  protocol:
    port: -1
    name: consumer
  application:
      name: sharp-cms
  registry:
      protocol: zookeeper
      address:  192.168.80.44:2181
spring:
  freemarker:
    cache: false
    template-loader-path: classpath:/WEB-INF

